### ISSUE TITLE
Broken links on page 'https://dnssec-tools.org/test/'

### ISSUE THREAD

**Issue by QuantumLibet** [DNSSEC-Tools/DNSSEC-Tools#18]
Just a quick heads up, if not already known:

The page 'https://dnssec-tools.org/test/' has a few broken links:
- The link behind the word 'read instructions' of the sentence "Learn how to sign your zone: read instructions" points to 'https://dnssec-tools.org/wiki/index.php/Sign_Your_Zone', which should probably be 'https://dnssec-tools.org/wiki/Sign_Your_Zone.html' instead.
- The link behind the word 'DNSSEC-Check' of the sentence "Check your network's support for DNSSEC with DNSSEC-Check" points to 'https://dnssec-tools.org/dnssec-check/', which should probably be 'http://dnssec-tools.org/download/#gotoDNSSEC-Check' instead.

This issue is posted in the spirit of helping, not to annoy anybody. Feel free to close it, if already known. Thank you for providing DNSSEC-Tools and have a very nice day.

**Comment by QuantumLibet** [comment]
Almost two years later the problem is still the same, and I still don't know how to fix it.

Since the above post seems to be interesting to nobody but me, I'll close it now. No sense leaving it open.

**Comment by hardaker** [comment]
Well, this did poke me into actually chasing down the problem.  It revealed a bunch of other problems I still need to take care of (including trying again to look for a good wiki -> md converter).  But, the /test page now has working links (and the thumbs up is currently a question mark since the test is currently not working).
